apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sleep-chart.fullname" . }}
  labels:
    {{- include "sleep-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sleep-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "finops-operator-exporter-chart.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "finops-operator-exporter-chart.fullname" . }}
        image: ghcr.io/krateoplatformops/alpine-sleep:3.21.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
